version: "3.8"

services:

  app:
    container_name: fastapi_app
    build: .
    command: bash -c "gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env-dckr
    depends_on:
      - redis
      - flower
      - celery
    restart: always

  redis:
    image: redis:7
    container_name: redis_server
    command: --port 6379
    expose:
      - 6379

  celery:
    build: .
    container_name: celery_app
    command: bash -c "celery --app=app.blog.repository.tasks:celery_app worker -l INFO"
    env_file:
      - .env-dckr
    depends_on:
      - redis

  flower:
    build: .
    container_name: flower_app
    command: bash -c "celery --app=app.blog.repository.tasks:celery_app flower"
    env_file:
      - .env-dckr
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555

